### ISSUE TITLE
Summernote Update

### ISSUE THREAD

**Issue by Tangol** [robiso/wondercms-plugins#1]
Please note that **Summernote** needs an update to **[v0.8.8](https://github.com/summernote/summernote/releases)** for it to support Bootstrap 4.

Also, could you please enable by default, all the Summernote editor [options](https://summernote.org/deep-dive/), like Font Family, Tables etc. ?

Thanks!

**Comment by robiso** [comment]
Sine we won't be implementing Bootstrap 4 just yet, this will come later in 2018, I will check into this if I can fit it into the next update.
The Summernote editor options are in plugins/summernote/summernote.php and can be easily customized for any variations.

If you need any assistance, please open a support post in the community.
I'll check if I can update the Summernote editor anyway.
